# Generated by Django 5.2.1 on 2025-05-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_alter_blog_content_alter_blog_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='genre',
            field=models.CharField(choices=[('accion', 'Acción'), ('comedia', 'Comedia'), ('drama', 'Drama'), ('terror', 'Terror'), ('romance', 'Romance'), ('documental', 'Documental'), ('animacion', 'Animación')], default='Sin género', max_length=20),
            preserve_default=False,
        ),
    ]
